<?php

namespace App\Entity;

use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use DateTimeImmutable;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\File;

#[ORM\Entity]
#[ORM\Table(name: "clients")]
#[ORM\InheritanceType("JOINED")]
#[ORM\DiscriminatorColumn(name: "discr", type: "string")]
#[ORM\DiscriminatorMap(["client" => Client::class, "verifiedClient" => VerifiedClient::class])]
class Client extends User
{
    #[ORM\Column(type: "boolean")]
    private bool $verificationStatus = false;

    #[ORM\Column(type: "datetime_immutable")]
    private \DateTimeImmutable $dateInscription;

    #[ORM\Column(type: "integer")]
    private int $loyaltyPoints = 0;

    #[ORM\OneToMany(targetEntity: Review::class, mappedBy: "client")]
    private Collection $reviews;

    #[ORM\OneToMany(targetEntity: Vehicule::class, mappedBy: "client")]
    private Collection $vehicules;

    #[ORM\OneToMany(targetEntity: Critique::class, mappedBy: "client")]
    private Collection $critiques;

    #[ORM\OneToOne(targetEntity: Cart::class, mappedBy: 'client')]
    private ?Cart $cart = null;

    #[ORM\OneToMany(targetEntity: Complaint::class, mappedBy: "client")]
    private Collection $complaints;

    #[ORM\Column(type: "string", length: 500, nullable: true)]
    #[Vich\UploadableField(mapping: 'user_upload', fileNameProperty: 'photoProfil')]
    private ?File $ClientphotoProfilFile = null;

    public function setRoles(string $roles): User
    {
        $roles="CLIENT";
        return parent::setRoles($roles); // TODO: Change the autogenerated stub
    }

    // Constructor
    public function __construct(
        string $name = '',
        string $email = '',
        ?string $adress = null,

        string $roles = "client",
        string $password = '',
        string $city = '',
        ?string $resetToken = null,
        ?DateTimeInterface $tokenExpiration = null,
        bool $verificationStatus = false,
        ?string $phone = null,
        string $photoProfil = null
    ) {
        parent::__construct($name, $email, $roles, $password,$city, $resetToken, $tokenExpiration, $phone, $photoProfil);

        // Initialize Client-specific properties
        $this->username = $name;
        $this->setRoles($roles);
        $this->dateInscription = new DateTimeImmutable();
        $this->verificationStatus = $verificationStatus;

        // Initialize collections
        $this->reviews = new ArrayCollection();
        $this->vehicules = new ArrayCollection();
        $this->critiques = new ArrayCollection();
        $this->carts = new ArrayCollection();
        $this->complaints = new ArrayCollection();

        // If you want to initialize the profile photo in the constructor, use the setter:
    }

    // Getter and setter for the uploaded file
    public function getClientphotoProfilFile(): ?File
    {
        return $this->ClientphotoProfilFile;
    }

    public function setClientphotoProfilFile(?File $ClientphotoProfilFile): void
    {
        $this->ClientphotoProfilFile = $ClientphotoProfilFile;
        if ($ClientphotoProfilFile) {
            // Trigger file upload immediately
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    // Getter and setter for the filename (photo profile)


    






    // Other getters and setters
    public function isVerificationStatus(): bool
    {
        return $this->verificationStatus;
    }

    public function setVerificationStatus(bool $verificationStatus): void
    {
        $this->verificationStatus = $verificationStatus;
    }

    public function getDateInscription(): \DateTimeImmutable
    {
        return $this->dateInscription;
    }

    public function setDateInscription(\DateTimeImmutable $dateInscription): void
    {
        $this->dateInscription = $dateInscription;
    }

    public function getLoyaltyPoints(): int
    {
        return $this->loyaltyPoints;
    }

    public function setLoyaltyPoints(int $loyaltyPoints): void
    {
        $this->loyaltyPoints = $loyaltyPoints;
    }

    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function setReviews(Collection $reviews): void
    {
        $this->reviews = $reviews;
    }

    public function getVehicules(): Collection
    {
        return $this->vehicules;
    }

    public function setVehicules(Collection $vehicules): void
    {
        $this->vehicules = $vehicules;
    }

    public function getCritiques(): Collection
    {
        return $this->critiques;
    }

    public function setCritiques(Collection $critiques): void
    {
        $this->critiques = $critiques;
    }

    public function getComplaints(): Collection
    {
        return $this->complaints;
    }

    public function setComplaints(Collection $complaints): void
    {
        $this->complaints = $complaints;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(?string $username): void
    {
        $this->username = $username;
    }
}
