const Encore = require('@symfony/webpack-encore');
const webpack = require('webpack'); // Keep this if you needed webpack for other things, but not needed for ProvidePlugin with Encore

// Manually configure the runtime environment
if (!Encore.isRuntimeEnvironmentConfigured()) {
    Encore.configureRuntimeEnvironment(process.env.NODE_ENV || 'dev');
}

Encore
    .setOutputPath('public/build/')
    .setPublicPath('/build')

    // Define your entry points
    .addEntry('app', './assets/app.js')
    //.addStyleEntry('styles', './assets/main.css') // Use 'styles' or any name you like
   // .addEntry('main', './assets/main.js')
    // If main.js imports CSS/SCSS, that's fine.
    // If you had a separate CSS/SCSS file as an entry, use addStyleEntry:
    // .addStyleEntry('styles', './assets/main.scss')

    // Basic Encore features
    .splitEntryChunks()
    .enableSingleRuntimeChunk()
    .cleanupOutputBeforeBuild()
    .enableBuildNotifications()
    .enableSourceMaps(!Encore.isProduction())
    .enableVersioning(Encore.isProduction())

    // Configure Babel for polyfills (core-js)
    .configureBabelPresetEnv((config) => {
        config.useBuiltIns = 'usage';
        config.corejs = '3.38'; // Make sure 'core-js' version 3.38+ is in your package.json
    })

    // Enable SASS/SCSS loader
    .enableSassLoader(options => {
        options.implementation = require('sass');
        options.sassOptions = {
            outputStyle: 'compressed' // Use 'expanded' in dev if preferred
        };
    })

    // Enable PostCSS loader (important for autoprefixing, etc.)
    .enablePostCssLoader() // Ensure this is called

    // Provide jQuery automatically (this replaces the need for webpack.ProvidePlugin for jQuery)
    .autoProvidejQuery()

    // Enable Stimulus bridge if using Stimulus controllers
    .enableStimulusBridge('./assets/controllers.json')

    // Custom loader configurations (Keep these within the chain)
    .configureLoaderRule('js', loaderRule => {
        // Exclude .map files from babel-loader processing (generally okay)
        loaderRule.exclude = /\.map$/;
    })
    // --- Removed configureLoaderRule('css', ...) ---
    // It's generally safer to let Encore handle CSS rules set up by enableSassLoader/enablePostCssLoader
    // unless you have a specific, known reason to modify them. Removing this simplifies things.

    .configureLoaderRule('images', loaderRule => {
        // This rule handles images AND fonts as defined by the regex
        loaderRule.test = /\.(png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$/;
        // Encore's default asset/resource rule is usually sufficient,
        // but this explicit rule is fine if you prefer it.
    })

// --- Removed the incorrect module.exports = { plugins: [...] } block ---
// ProvidePlugin for jQuery is handled by .autoProvidejQuery() above.
// If you need *other* webpack plugins, add them using Encore.addPlugin():
// .addPlugin(new YourOtherWebpackPlugin())
;

// Export the final configuration object generated by Encore
module.exports = Encore.getWebpackConfig();