# config/services.yaml

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Service\WhatsAppVerificationCodeSender:
        arguments:
            $twilioSid: '%env(TWILIO_ACCOUNT_SID)%'
            $twilioToken: '%env(TWILIO_AUTH_TOKEN)%'
            $verifyServiceSid: '%env(TWILIO_VERIFY_SERVICE_SID)%'