parameters:
    upload_directory: '%kernel.project_dir%/public/uploads'
    TWILIO_ACCOUNT_SID: '%env(TWILIO_ACCOUNT_SID)%'
    TWILIO_AUTH_TOKEN: '%env(TWILIO_AUTH_TOKEN)%'
    TWILIO_FROM_NUMBER: '%env(TWILIO_FROM_NUMBER)%'
    TWILIO_CONTENT_SID: '%env(TWILIO_CONTENT_SID)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    Twilio\Rest\Client:
        arguments:
            - '%TWILIO_ACCOUNT_SID%'
            - '%TWILIO_AUTH_TOKEN%'

    App\Service\AuthClient\WhatsAppVerificationCodeSender:
        arguments:
            $twilio: '@Twilio\Rest\Client'
            $cache: '@cache.app'
            $logger: '@logger'
            $twilioFromNumber: '%TWILIO_FROM_NUMBER%'
            $twilioContentSid: '%TWILIO_CONTENT_SID%'

    App\Service\FileUploader:
        arguments:
            $targetDirectory: '%upload_directory%'
