# config/packages/monolog.yaml

monolog:
    channels: ["security"]  # Define the "security" channel

    handlers:
        # Main handler logs to the environment log
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]

        # Security handler logs specifically for security-related logs
        security:
            type: stream
            path: "%kernel.logs_dir%/security.log"
            level: info
            channels: ["security"]

        # Log to stderr for all logs at the debug level
        stderr:
            type: stream
            path: "php://stderr"
            level: debug

        # Console handler for command line logging
        console:
            type: console
            process_psr_3_messages: false

# When in the development environment, logging specifics:
when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]

            # You can uncomment this for logging to FirePHP (debugging in browsers)
            # firephp:
            #     type: firephp
            #     level: info

            # You can uncomment this for logging to ChromePHP (debugging in browsers)
            # chromephp:
            #     type: chromephp
            #     level: info

            # Console handler for the development environment
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

# When in the test environment, use more specific handlers
when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

# When in the production environment, handle logging with more focus
when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # Prevent memory leaks, manage buffer size
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json

            # Console handler in production (exclude event and doctrine)
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]

            # Separate handler for deprecation notices
            deprecation:
                type: stream
