# config/packages/webpack_encore.yaml
webpack_encore:
    # The path where Encore is building the assets - i.e. Encore.setOutputPath()
    output_path: '%kernel.project_dir%/public/build'
    
    # Set attributes that will be rendered on all script and link tags
    script_attributes:
        defer: true
        # Uncomment if using Turbo Drive
        # 'data-turbo-track': reload

    # Uncomment if using Turbo Drive
    # link_attributes:
        # 'data-turbo-track': reload

    # If using Encore.enableIntegrityHashes() and need the crossorigin attribute
    # crossorigin: 'anonymous'

    # Preload all rendered script and link tags automatically via the HTTP/2 Link header
    # preload: true

    # Throw an exception if the entrypoints.json file is missing or an entry is missing
    strict_mode: false

    # If you have multiple builds, you can define them here
    # builds:
    #     frontend: '%kernel.project_dir%/public/frontend/build'

framework:
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
